site_name: fdray
site_url: https://daizutabi.github.io/fdray/
site_description: Python Ray Tracing Interface for POV-Ray
site_author: daizutabi
repo_url: https://github.com/daizutabi/fdray/
repo_name: daizutabi/fdray
edit_uri: edit/main/docs/
theme:
  name: material
  font:
    text: Fira Sans
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
plugins:
  - search
  - mkdocs-nbsync:
      src_dir: ../notebooks
  - mkapi:
      debug: true
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Tutorial:
      - tutorial/camera.md
      - tutorial/light_source.md
      - Object:
          - tutorial/object/primitives.md
          - tutorial/object/transformations.md
      #     - notebooks/object/csg.ipynb
      # - Texture:
      #     - notebooks/texture/pigment.ipynb
      #     - notebooks/texture/normal.ipynb
      #     - notebooks/texture/finish.ipynb
      #     - notebooks/texture/pattern.ipynb
      #     - notebooks/texture/interior_texture.ipynb
      # - Media:
      #     - notebooks/media/interior.ipynb
      # - Data Visualization:
      #     - notebooks/data/region.ipynb
      #     - notebooks/data/field.ipynb
  - Reference: $api/fdray.***
